spring.application.name=thiserver

<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/do_an_thi_online
spring.datasource.username=root
spring.datasource.password=kien0310

>>>>>>> loi_dao
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
